name: Flames
description: FRIENDS,LOVE,AFFECTION,MARRIAGE,ENEMY,SIBLINGS
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"

flutter:

  uses-material-design: true
  assets:
   - assets/img/icon.png